### ISSUE TITLE
React error for Dropdown Storybook

### ISSUE THREAD

**Issue by Nick-Mazuk** [supabase/ui#159]
# Bug report

## Describe the bug

When changing the "visibility" to "true" for the Dropdown component, you get this error:

```
Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ch (https://ui.supabase.com/vendors~main.b9d7abc50bff0ca1dee6.bundle.js:2:1524002)
    at li (https://ui.supabase.com/vendors~main.b9d7abc50bff0ca1dee6.bundle.js:2:1533434)
    at ck (https://ui.supabase.com/vendors~main.b9d7abc50bff0ca1dee6.bundle.js:2:1577140)
    at bk (https://ui.supabase.com/vendors~main.b9d7abc50bff0ca1dee6.bundle.js:2:1563243)
    at ak (https://ui.supabase.com/vendors~main.b9d7abc50bff0ca1dee6.bundle.js:2:1563174)
    at Tj (https://ui.supabase.com/vendors~main.b9d7abc50bff0ca1dee6.bundle.js:2:1563043)
    at Lj (https://ui.supabase.com/vendors~main.b9d7abc50bff0ca1dee6.bundle.js:2:1560068)
    at https://ui.supabase.com/vendors~main.b9d7abc50bff0ca1dee6.bundle.js:2:1509853
    at exports.unstable_runWithPriority (https://ui.supabase.com/vendors~main.b9d7abc50bff0ca1dee6.bundle.js:2:1587158)
    at gg (https://ui.supabase.com/vendors~main.b9d7abc50bff0ca1dee6.bundle.js:2:1509630)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://ui.supabase.com/?path=/story/navigation-dropdown--default
2. Change the "visibility" control to "true"

## Screenshots

<img width="1536" alt="Screen Shot 2021-03-26 at 8 43 52 PM" src="https://user-images.githubusercontent.com/5659171/112709152-fc49a480-8e73-11eb-804d-ac52c74eed3d.png">

## System information

- OS: macOS 11.2.1
- Browser Brave 1.22.67

**Comment by MildTomato** [comment]
thanks @Nick-Mazuk !

**Comment by MildTomato** [comment]
Additional issue with Dropdown not working in react v17.0.01 / react-dom v17.0.01

**Comment by angelmtztrc** [comment]
I have the same issue, but, I think I found the solution, can I create a pull request?

![image](https://user-images.githubusercontent.com/65056245/113466903-a12c2a80-93fc-11eb-9dae-96295fe8b9ee.png)

**Comment by angelmtztrc** [comment]
> I have the same issue, but, I think I found the solution, can I create a pull request?
> 
> ![image](https://user-images.githubusercontent.com/65056245/113466903-a12c2a80-93fc-11eb-9dae-96295fe8b9ee.png)

I already see that you have a branch with the solution, so, that's cool!
