### ISSUE TITLE
Feat: Host Storybook docs website

### ISSUE THREAD

**Issue by MildTomato** [supabase/ui#4]
# Feature request

Deploy storybook docs website.
Also need to update instructions page in storybook

**Comment by kiwicopple** [comment]
FYI I tried these settings on Netlify 

<img width="477" alt="image" src="https://user-images.githubusercontent.com/10214025/103643899-6ac34880-4f90-11eb-86dc-9ce9c612bb1d.png">



and got this error:

```
12:54:09 PM: info => Loading presets
12:54:10 PM: WARN   Failed to load preset: "/opt/build/repo/node_modules/@storybook/core/dist/server/manager/manager-preset.js"
12:54:10 PM: ERR! Error: Cannot find module 'react/package.json'
12:54:10 PM: ERR! Require stack:
12:54:10 PM: ERR! - /opt/build/repo/node_modules/@storybook/ui/noop.js
12:54:10 PM: ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
12:54:10 PM: ERR!     at resolveFileName (/opt/build/repo/node_modules/resolve-from/index.js:29:39)
12:54:10 PM: ERR!     at resolveFrom (/opt/build/repo/node_modules/resolve-from/index.js:43:9)
12:54:10 PM: ERR!     at module.exports (/opt/build/repo/node_modules/resolve-from/index.js:46:47)
12:54:10 PM: ERR!     at Object.<anonymous> (/opt/build/repo/node_modules/@storybook/ui/paths.js:17:18)
12:54:10 PM: ERR!     at Module._compile (internal/modules/cjs/loader.js:1138:30)
12:54:10 PM: ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
12:54:10 PM: ERR!     at Module.load (internal/modules/cjs/loader.js:986:32)
12:54:10 PM: ERR!     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
12:54:10 PM: ERR!     at Module.require (internal/modules/cjs/loader.js:1026:19)
12:54:10 PM: ERR!     at require (internal/modules/cjs/helpers.js:72:18)
12:54:10 PM: ERR!     at Object.<anonymous> (/opt/build/repo/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js:34:38)
12:54:10 PM: ERR!     at Module._compile (internal/modules/cjs/loader.js:1138:30)
12:54:10 PM: ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
12:54:10 PM: ERR!     at Module.load (internal/modules/cjs/loader.js:986:32)
12:54:10 PM: ERR!     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
12:54:10 PM: ERR!  Error: Cannot find module 'react/package.json'
12:54:10 PM: ERR! Require stack:
12:54:10 PM: ERR! - /opt/build/repo/node_modules/@storybook/ui/noop.js
12:54:10 PM: ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
12:54:10 PM: ERR!     at resolveFileName (/opt/build/repo/node_modules/resolve-from/index.js:29:39)
12:54:10 PM: ERR!     at resolveFrom (/opt/build/repo/node_modules/resolve-from/index.js:43:9)
12:54:10 PM: ERR!     at module.exports (/opt/build/repo/node_modules/resolve-from/index.js:46:47)
12:54:10 PM: ERR!     at Object.<anonymous> (/opt/build/repo/node_modules/@storybook/ui/paths.js:17:18)
12:54:10 PM: ERR!     at Module._compile (internal/modules/cjs/loader.js:1138:30)
12:54:10 PM: ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
12:54:10 PM: ERR!     at Module.load (internal/modules/cjs/loader.js:986:32)
12:54:10 PM: ERR!     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
12:54:10 PM: ERR!     at Module.require (internal/modules/cjs/loader.js:1026:19)
12:54:10 PM: ERR!     at require (internal/modules/cjs/helpers.js:72:18)
12:54:10 PM: ERR!     at Object.<anonymous> (/opt/build/repo/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js:34:38)
12:54:10 PM: ERR!     at Module._compile (internal/modules/cjs/loader.js:1138:30)
12:54:10 PM: ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
12:54:10 PM: ERR!     at Module.load (internal/modules/cjs/loader.js:986:32)
12:54:10 PM: ERR!     at Function.Module._load (internal/modules/cjs/loader.js:879:14) {
12:54:10 PM: ERR!   code: 'MODULE_NOT_FOUND',
12:54:10 PM: ERR!   requireStack: [ '/opt/build/repo/node_modules/@storybook/ui/noop.js' ]
12:54:10 PM: ERR! }
12:54:10 PM: WARN unable to find package.json for @rollup/plugin-node-resolve
12:54:10 PM: WARN unable to find package.json for rollup
12:54:10 PM: info => Compiling manager..
12:54:11 PM: ERR! => Failed to build the manager
12:54:11 PM: ERR! ./src/index.js
```

You may have more luck ...

**Comment by MildTomato** [comment]
@joshenlim had almost the exact same error running storybook locally.

turns out it's because react-dom is just a peer dependency, but should also (maybe?) be a dev dependency as well.

@joshenlim your changes on your chore branch will probably fix this
